# netlify.toml
[build]
  # não declare 'command' quando não há build
  publish   = "."                        # publica a raiz
  functions = "netlify/functions"        # pasta das Netlify Functions

[[redirects]]
  from   = "/"                           # raiz do site
  to     = "/BemVindo.html"              # página inicial
  status = 200
  force  = true
